### ISSUE TITLE
Hard delete fails

### ISSUE THREAD

**Issue by GoogleCodeExporter** [LeoLiXX/dataloadercliq#44]
```
What steps will reproduce the problem?
1. Set up export CLIq process on desired custom object
2. Set up hard delete CLIq process on desired custom object
3. Run CLIq export process (will output the ids of objects)
4. Copy output (write) file to input (read) of CLIq delete process
5. Run CLIq hard delete process

What is the expected output? What do you see instead?
Expected hard delete of objects listed.  Nothing was written to error or 
success .csv file.  sdl.log noted the following:

2012-02-02 22:06:04,070 INFO  [CLIDeleteTest] action.OperationInfo 
instantiateAction (OperationInfo.java:62) - Instantiating action for operation: 
hard_delete
2012-02-02 22:06:04,070 FATAL [CLIDeleteTest] action.OperationInfo 
unsupportedInstantiation (OperationInfo.java:75) - Error instantiating 
operation hard_delete: could not instantiate class: null.
2012-02-02 22:06:04,071 FATAL [main] process.ProcessRunner topLevelError 
(ProcessRunner.java:212) - Unable to run process CLIDeleteTest
java.lang.RuntimeException: java.lang.UnsupportedOperationException: Error 
instantiating operation hard_delete: could not instantiate class: null.
    at com.salesforce.dataloader.process.ProcessRunner.run(ProcessRunner.java:137)
    at com.salesforce.dataloader.process.ProcessRunner.run(ProcessRunner.java:75)
    at com.salesforce.dataloader.process.ProcessRunner.main(ProcessRunner.java:227)
Caused by: java.lang.UnsupportedOperationException: Error instantiating 
operation hard_delete: could not instantiate class: null.
    at com.salesforce.dataloader.action.OperationInfo.unsupportedInstantiation(OperationInfo.java:76)
    at com.salesforce.dataloader.action.OperationInfo.instantiateAction(OperationInfo.java:68)
    at com.salesforce.dataloader.controller.Controller.executeAction(Controller.java:104)
    at com.salesforce.dataloader.process.ProcessRunner.run(ProcessRunner.java:124)
    ... 2 more
Caused by: java.lang.NullPointerException
    at com.salesforce.dataloader.action.OperationInfo.instantiateAction(OperationInfo.java:66)
    ... 4 more


What version of the product are you using? On what operating system?
This was done on Windows 7 Professional, SP 1.  Using CLIq version 2.1.1.


Please provide any additional information below.
Was able to execute soft delete successfully.  All other activities (insert, 
upsert, etc.) work fine.  Only problem is with hard delete.  User used for 
login has Bulk API Hard Delete enabled in profile.
```

Original issue reported on code.google.com by `smurph2...@gmail.com` on 2 Feb 2012 at 10:37

**Comment by GoogleCodeExporter** [comment]
```
What version of DataLoader.jar do you have?  I think hard delete is available 
from 21 or later.
```

Original comment by `vijay.swamidass@gmail.com` on 2 Feb 2012 at 10:51

**Comment by GoogleCodeExporter** [comment]
```
I am using DataLoader v 20.  The interface allows hard delete.  Do you mean
it is not available via the API?
```

Original comment by `smurph2...@gmail.com` on 3 Feb 2012 at 2:04

**Comment by GoogleCodeExporter** [comment]
```
See if this article helps:
http://success.salesforce.com/ideaView?id=08730000000Ik8w

The person was using this parameter:
<entry key="sfdc.useBulkApi" value="true"/>

Try adding that to your process-conf.xml.  If that works, I can add it to the 
CLIq config.
I think the person was also using DL 21.0.
```

Original comment by `vijay.swamidass@gmail.com` on 3 Feb 2012 at 2:22

**Comment by GoogleCodeExporter** [comment]
```
That worked.  The entry appears in the process-conf.xml file, but the value
is set to "false" for the hard delete action (by default I guess).  Thanks
for the help!

Michael
```

Original comment by `smurph2...@gmail.com` on 3 Feb 2012 at 3:07

**Comment by GoogleCodeExporter** [comment]
Original comment by `vijay.swamidass@gmail.com` on 3 Feb 2012 at 4:53
- Changed state: **Accepted**

**Comment by GoogleCodeExporter** [comment]
Original comment by `vijay.swamidass@gmail.com` on 16 Oct 2012 at 4:52
- Changed state: **Done**
