### ISSUE TITLE
Cant login when scheduled?

### ISSUE THREAD

**Issue by GoogleCodeExporter** [LeoLiXX/dataloadercliq#54]
```
What steps will reproduce the problem?
1. Created the batch file
2. Scheduled it to run using windows scheduler
3.

What is the expected output? What do you see instead?
Data is not upserte. sdl file (below) show timeout errors
I can run the batch file manually by clicking on it, it only ever fails when it 
is scheduled


What version of the product are you using? On what operating system?
lastest version on windows 7 server

Please provide any additional information below.
-06-10 22:00:02,745 INFO  [main] controller.Controller initLog 
(Controller.java:404) - The log has been initialized
2012-06-10 22:00:02,761 INFO  [main] process.ProcessConfig getBeanFactory 
(ProcessConfig.java:103) - Loading process configuration from config file: 
C:\Program Files\salesforce.com\Data 
Loader\cliq_process\BMW_Vehicles\config\process-conf.xml
2012-06-10 22:00:03,073 INFO  [main] xml.XmlBeanDefinitionReader 
loadBeanDefinitions (XmlBeanDefinitionReader.java:315) - Loading XML bean 
definitions from file [C:\Program Files\salesforce.com\Data 
Loader\cliq_process\BMW_Vehicles\config\process-conf.xml]
2012-06-10 22:00:03,291 INFO  [BMW_Vehicles] controller.Controller initConfig 
(Controller.java:365) - The controller config has been initialized
2012-06-10 22:00:03,291 INFO  [BMW_Vehicles] process.ProcessRunner run 
(ProcessRunner.java:116) - Initializing process engine
2012-06-10 22:00:03,291 INFO  [BMW_Vehicles] process.ProcessRunner run 
(ProcessRunner.java:119) - Loading parameters
2012-06-10 22:00:09,937 INFO  [BMW_Vehicles] config.LastRun load 
(LastRun.java:96) - Last run info will be saved in file: C:\Program 
Files\salesforce.com\Data 
Loader\cliq_process\BMW_Vehicles\log\BMW_Vehicles_lastRun.properties
2012-06-10 22:00:09,952 INFO  [BMW_Vehicles] process.ProcessRunner run 
(ProcessRunner.java:127) - Logging in to: https://login.salesforce.com
2012-06-10 22:00:10,015 INFO  [BMW_Vehicles] client.PartnerClient login 
(PartnerClient.java:478) - Beginning Partner Salesforce login ....
2012-06-10 22:00:10,030 INFO  [BMW_Vehicles] client.PartnerClient loginInternal 
(PartnerClient.java:519) - Salesforce login to 
https://login.salesforce.com/services/Soap/u/24.0 as user hrowen@tquila.com
2012-06-10 22:00:29,543 ERROR [BMW_Vehicles] client.PartnerClient runOperation 
(PartnerClient.java:332) - Error while calling web service operation: login, 
error was: Failed to send request to 
https://login.salesforce.com/services/Soap/u/24.0
com.sforce.ws.ConnectionException: Failed to send request to 
https://login.salesforce.com/services/Soap/u/24.0
    at com.sforce.ws.transport.SoapConnection.send(SoapConnection.java:120)
    at com.sforce.soap.partner.PartnerConnection.login(PartnerConnection.java:954)
    at com.salesforce.dataloader.client.PartnerClient$8.run(PartnerClient.java:161)
    at com.salesforce.dataloader.client.PartnerClient$8.run(PartnerClient.java:152)
    at com.salesforce.dataloader.client.PartnerClient.runOperation(PartnerClient.java:328)
    at com.salesforce.dataloader.client.PartnerClient.loginInternal(PartnerClient.java:520)
    at com.salesforce.dataloader.client.PartnerClient.login(PartnerClient.java:488)
    at com.salesforce.dataloader.client.PartnerClient.connect(PartnerClient.java:213)
    at com.salesforce.dataloader.controller.Controller.login(Controller.java:176)
    at com.salesforce.dataloader.controller.Controller.login(Controller.java:171)
    at com.salesforce.dataloader.process.ProcessRunner.run(ProcessRunner.java:128)
    at com.salesforce.dataloader.process.ProcessRunner.run(ProcessRunner.java:100)
    at com.salesforce.dataloader.process.ProcessRunner.main(ProcessRunner.java:253)
Caused by: java.net.ConnectException: Connection timed out: connect
    at java.net.PlainSocketImpl.socketConnect(Native Method)
    at java.net.PlainSocketImpl.doConnect(Unknown Source)
    at java.net.PlainSocketImpl.connectToAddress(Unknown Source)
    at java.net.PlainSocketImpl.connect(Unknown Source)
    at java.net.SocksSocketImpl.connect(Unknown Source)
    at java.net.Socket.connect(Unknown Source)
    at com.sun.net.ssl.internal.ssl.SSLSocketImpl.connect(Unknown Source)
    at sun.net.NetworkClient.doConnect(Unknown Source)
    at sun.net.www.http.HttpClient.openServer(Unknown Source)
    at sun.net.www.http.HttpClient.openServer(Unknown Source)
    at sun.net.www.protocol.https.HttpsClient.<init>(Unknown Source)
    at sun.net.www.protocol.https.HttpsClient.New(Unknown Source)
    at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(Unknown Source)
    at sun.net.www.protocol.http.HttpURLConnection.plainConnect(Unknown Source)
    at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(Unknown Source)
    at sun.net.www.protocol.http.HttpURLConnection.getOutputStream(Unknown Source)
    at sun.net.www.protocol.https.HttpsURLConnectionImpl.getOutputStream(Unknown Source)
    at com.sforce.ws.transport.JdkHttpTransport.connectRaw(JdkHttpTransport.java:133)
    at com.sforce.ws.transport.JdkHttpTransport.connectLocal(JdkHttpTransport.java:97)
    at com.sforce.ws.transport.JdkHttpTransport.connectLocal(JdkHttpTransport.java:92)
    at com.sforce.ws.transport.JdkHttpTransport.connect(JdkHttpTransport.java:88)
    at com.sforce.ws.transport.SoapConnection.send(SoapConnection.java:94)
    ... 12 more
2012-06-10 22:00:29,590 ERROR [BMW_Vehicles] client.PartnerClient loginInternal 
(PartnerClient.java:534) 
```

Original issue reported on code.google.com by `paddybut...@gmail.com` on 10 Jun 2012 at 11:03

**Comment by GoogleCodeExporter** [comment]
```
I have tried both https://login.salesforce.com/services/Soap/u/24.0  and 
https://login.salesforce.com/ as the endpoints in the xml file but neither work 
when the file is scheduled.
Both endpoints work when I run the batch file by clicking on it.
```

Original comment by `paddybut...@gmail.com` on 10 Jun 2012 at 11:05

**Comment by GoogleCodeExporter** [comment]
```
That is strange.  If it works when clicking on it, then it must not be a CLIq 
specific issue.  Is there a firewall or some other security process that would 
block the scheduled process?
```

Original comment by `vijay.swamidass@gmail.com` on 11 Jun 2012 at 5:37

**Comment by GoogleCodeExporter** [comment]
```
turned uac to lowest possible level and windows firewall is turned off
```

Original comment by `paddybut...@gmail.com` on 11 Jun 2012 at 8:42

**Comment by GoogleCodeExporter** [comment]
```
The UAC resolved some of the issues and most of the batch files now run but 
some have the following error:

NFO  [JackBarclay_Accounts] process.ProcessRunner run (ProcessRunner.java:132) 
- Checking the data access object connection
2012-06-11 09:26:30,494 INFO  [JackBarclay_Accounts] process.ProcessRunner run 
(ProcessRunner.java:137) - Setting field types
2012-06-11 09:26:31,435 INFO  [JackBarclay_Accounts] process.ProcessRunner run 
(ProcessRunner.java:141) - Setting object reference types
2012-06-11 09:26:33,002 INFO  [JackBarclay_Accounts] process.ProcessRunner run 
(ProcessRunner.java:145) - Creating Map
2012-06-11 09:26:33,014 INFO  [JackBarclay_Accounts] action.OperationInfo 
instantiateAction (OperationInfo.java:95) - Instantiating action for operation: 
upsert
2012-06-11 09:26:33,065 INFO  [JackBarclay_Accounts] controller.Controller 
executeAction (Controller.java:123) - executing operation: upsert
2012-06-11 09:26:33,066 INFO  [JackBarclay_Accounts] action.AbstractAction 
execute (AbstractAction.java:115) - Loading: upsert
2012-06-11 09:26:33,692 INFO  [JackBarclay_Accounts] 
progress.NihilistProgressAdapter setSubTask (NihilistProgressAdapter.java:78) - 
Processed 1 of 1 total records. Rate: 5,000 records per hour. Estimated time to 
complete: 0 minutes and 0 seconds.  There are 1 successes and 0 errors.
2012-06-11 09:26:33,695 INFO  [JackBarclay_Accounts] 
progress.NihilistProgressAdapter doneSuccess (NihilistProgressAdapter.java:63) 
- The operation has fully completed.  There were 1 successful upserts and 0 
errors.
2012-06-12 01:00:07,261 INFO  [main] controller.Controller initLog 
(Controller.java:404) - The log has been initialized
2012-06-12 01:00:07,276 INFO  [main] process.ProcessConfig getBeanFactory 
(ProcessConfig.java:103) - Loading process configuration from config file: 
C:\Program Files\salesforce.com\Data 
Loader\cliq_process\JackBarclay_Accounts\config\process-conf.xml
2012-06-12 01:00:07,807 INFO  [main] xml.XmlBeanDefinitionReader 
loadBeanDefinitions (XmlBeanDefinitionReader.java:315) - Loading XML bean 
definitions from file [C:\Program Files\salesforce.com\Data 
Loader\cliq_process\JackBarclay_Accounts\config\process-conf.xml]
2012-06-12 01:00:08,041 INFO  [JackBarclay_Accounts] controller.Controller 
initConfig (Controller.java:365) - The controller config has been initialized
2012-06-12 01:00:08,041 INFO  [JackBarclay_Accounts] process.ProcessRunner run 
(ProcessRunner.java:116) - Initializing process engine
2012-06-12 01:00:08,041 INFO  [JackBarclay_Accounts] process.ProcessRunner run 
(ProcessRunner.java:119) - Loading parameters
2012-06-12 01:00:15,466 INFO  [JackBarclay_Accounts] config.LastRun load 
(LastRun.java:96) - Last run info will be saved in file: C:\Program 
Files\salesforce.com\Data 
Loader\cliq_process\JackBarclay_Accounts\log\JackBarclay_Accounts_lastRun.proper
ties
2012-06-12 01:00:15,607 INFO  [JackBarclay_Accounts] process.ProcessRunner run 
(ProcessRunner.java:127) - Logging in to: https://login.salesforce.com
2012-06-12 01:00:15,669 INFO  [JackBarclay_Accounts] client.PartnerClient login 
(PartnerClient.java:478) - Beginning Partner Salesforce login ....
2012-06-12 01:00:15,685 INFO  [JackBarclay_Accounts] client.PartnerClient 
loginInternal (PartnerClient.java:519) - Salesforce login to 
https://login.salesforce.com/services/Soap/u/24.0 as user hrowen@tquila.com
2012-06-12 01:00:20,755 INFO  [JackBarclay_Accounts] 
dao.DataAccessObjectFactory getDaoInstance (DataAccessObjectFactory.java:51) - 
Instantiating data access object: C:\Program Files\salesforce.com\Data 
Loader\cliq_process\JackBarclay_Accounts\read\JackBarclay_Accounts.csv of type: 
csvRead
2012-06-12 01:00:20,755 INFO  [JackBarclay_Accounts] process.ProcessRunner run 
(ProcessRunner.java:132) - Checking the data access object connection
2012-06-12 01:00:20,786 INFO  [JackBarclay_Accounts] process.ProcessRunner run 
(ProcessRunner.java:137) - Setting field types
2012-06-12 01:00:41,846 ERROR [JackBarclay_Accounts] client.PartnerClient 
runOperation (PartnerClient.java:332) - Error while calling web service 
operation: describeSObject, error was: Failed to send request to 
https://eu1-api.salesforce.com/services/Soap/u/24.0/00D90000000cxCM
com.sforce.ws.ConnectionException: Failed to send request to 
https://eu1-api.salesforce.com/services/Soap/u/24.0/00D90000000cxCM
    at com.sforce.ws.transport.SoapConnection.send(SoapConnection.java:120)
    at com.sforce.soap.partner.PartnerConnection.describeSObject(PartnerConnection.java:1115)
    at com.salesforce.dataloader.client.PartnerClient$10.run(PartnerClient.java:185)
    at com.salesforce.dataloader.client.PartnerClient$10.run(PartnerClient.java:177)
    at com.salesforce.dataloader.client.PartnerClient.runOperation(PartnerClient.java:328)
    at com.salesforce.dataloader.client.PartnerClient.describeSObject(PartnerClient.java:723)
    at com.salesforce.dataloader.client.PartnerClient.setFieldTypes(PartnerClient.java:676)
    at com.salesforce.dataloader.controller.Controller.setFieldTypes(Controller.java:133)
    at com.salesforce.dataloader.process.ProcessRunner.run(ProcessRunner.java:138)
    at com.salesforce.dataloader.process.ProcessRunner.run(ProcessRunner.java:100)
    at com.salesforce.dataloader.process.ProcessRunner.main(ProcessRunner.java:253)
Caused by: java.net.ConnectException: Connection timed out: connect
    at java.net.PlainSocketImpl.socketConnect(Native Method)
    at java.net.PlainSocketImpl.doConnect(Unknown Source)
    at java.net.PlainSocketImpl.connectToAddress(Unknown Source)
    at java.net.PlainSocketImpl.connect(Unknown Source)
    at java.net.SocksSocketImpl.connect(Unknown Source)
    at java.net.Socket.connect(Unknown Source)
    at com.sun.net.ssl.internal.ssl.SSLSocketImpl.connect(Unknown Source)
    at sun.net.NetworkClient.doConnect(Unknown Source)
    at sun.net.www.http.HttpClient.openServer(Unknown Source)
    at sun.net.www.http.HttpClient.openServer(Unknown Source)
    at sun.net.www.protocol.https.HttpsClient.<init>(Unknown Source)
    at sun.net.www.protocol.https.HttpsClient.New(Unknown Source)
    at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(Unknown Source)
    at sun.net.www.protocol.http.HttpURLConnection.plainConnect(Unknown Source)
    at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(Unknown Source)
    at sun.net.www.protocol.http.HttpURLConnection.getOutputStream(Unknown Source)
    at sun.net.www.protocol.https.HttpsURLConnectionImpl.getOutputStream(Unknown Source)
    at com.sforce.ws.transport.JdkHttpTransport.connectRaw(JdkHttpTransport.java:133)
    at com.sforce.ws.transport.JdkHttpTransport.connectLocal(JdkHttpTransport.java:97)
    at com.sforce.ws.transport.JdkHttpTransport.connectLocal(JdkHttpTransport.java:92)
    at com.sforce.ws.transport.JdkHttpTransport.connect(JdkHttpTransport.java:88)
    at com.sforce.ws.transport.SoapConnection.send(SoapConnection.java:94)
    ... 10 more
2012-06-12 01:00:41,846 FATAL [main] process.ProcessRunner topLevelError 
(ProcessRunner.java:238) - Unable to run process JackBarclay_Accounts
java.lang.RuntimeException: com.sforce.ws.ConnectionException: Failed to send 
request to https://eu1-api.salesforce.com/services/Soap/u/24.0/00D90000000cxCM
    at com.salesforce.dataloader.process.ProcessRunner.run(ProcessRunner.java:162)
    at com.salesforce.dataloader.process.ProcessRunner.run(ProcessRunner.java:100)
    at com.salesforce.dataloader.process.ProcessRunner.main(ProcessRunner.java:253)
Caused by: com.sforce.ws.ConnectionException: Failed to send request to 
https://eu1-api.salesforce.com/services/Soap/u/24.0/00D90000000cxCM
    at com.sforce.ws.transport.SoapConnection.send(SoapConnection.java:120)
    at com.sforce.soap.partner.PartnerConnection.describeSObject(PartnerConnection.java:1115)
    at com.salesforce.dataloader.client.PartnerClient$10.run(PartnerClient.java:185)
    at com.salesforce.dataloader.client.PartnerClient$10.run(PartnerClient.java:177)
    at com.salesforce.dataloader.client.PartnerClient.runOperation(PartnerClient.java:328)
    at com.salesforce.dataloader.client.PartnerClient.describeSObject(PartnerClient.java:723)
    at com.salesforce.dataloader.client.PartnerClient.setFieldTypes(PartnerClient.java:676)
    at com.salesforce.dataloader.controller.Controller.setFieldTypes(Controller.java:133)
    at com.salesforce.dataloader.process.ProcessRunner.run(ProcessRunner.java:138)
    ... 2 more
Caused by: java.net.ConnectException: Connection timed out: connect
    at java.net.PlainSocketImpl.socketConnect(Native Method)
    at java.net.PlainSocketImpl.doConnect(Unknown Source)
    at java.net.PlainSocketImpl.connectToAddress(Unknown Source)
    at java.net.PlainSocketImpl.connect(Unknown Source)
    at java.net.SocksSocketImpl.connect(Unknown Source)
    at java.net.Socket.connect(Unknown Source)
    at com.sun.net.ssl.internal.ssl.SSLSocketImpl.connect(Unknown Source)
    at sun.net.NetworkClient.doConnect(Unknown Source)
    at sun.net.www.http.HttpClient.openServer(Unknown Source)
    at sun.net.www.http.HttpClient.openServer(Unknown Source)
    at sun.net.www.protocol.https.HttpsClient.<init>(Unknown Source)
    at sun.net.www.protocol.https.HttpsClient.New(Unknown Source)
    at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(Unknown Source)
    at sun.net.www.protocol.http.HttpURLConnection.plainConnect(Unknown Source)
    at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(Unknown Source)
    at sun.net.www.protocol.http.HttpURLConnection.getOutputStream(Unknown Source)
    at sun.net.www.protocol.https.HttpsURLConnectionImpl.getOutputStream(Unknown Source)
    at com.sforce.ws.transport.JdkHttpTransport.connectRaw(JdkHttpTransport.java:133)
    at com.sforce.ws.transport.JdkHttpTransport.connectLocal(JdkHttpTransport.java:97)
    at com.sforce.ws.transport.JdkHttpTransport.connectLocal(JdkHttpTransport.java:92)
    at com.sforce.ws.transport.JdkHttpTransport.connect(JdkHttpTransport.java:88)
    at com.sforce.ws.transport.SoapConnection.send(SoapConnection.java:94)
    ... 10 more

```

Original comment by `paddybut...@gmail.com` on 12 Jun 2012 at 12:19

**Comment by GoogleCodeExporter** [comment]
```
It is basically the same error message:
Failed to send request to 
https://eu1-api.salesforce.com/services/Soap/u/24.0/00D90000000cxCM

Do you have a proxy server? it seems like there is something blocking your 
request.
```

Original comment by `vijay.swamidass@gmail.com` on 12 Jun 2012 at 6:19

**Comment by GoogleCodeExporter** [comment]
```
There is no proxy, it seems to login but then there is an error when it calls 
the web service?

2012-06-13 04:45:02,897 INFO  [main] controller.Controller initLog 
(Controller.java:404) - The log has been initialized
2012-06-13 04:45:02,897 INFO  [main] process.ProcessConfig getBeanFactory 
(ProcessConfig.java:103) - Loading process configuration from config file: 
C:\Program Files\salesforce.com\Data 
Loader\cliq_process\BMW_Accounts\config\process-conf.xml
2012-06-13 04:45:03,240 INFO  [main] xml.XmlBeanDefinitionReader 
loadBeanDefinitions (XmlBeanDefinitionReader.java:315) - Loading XML bean 
definitions from file [C:\Program Files\salesforce.com\Data 
Loader\cliq_process\BMW_Accounts\config\process-conf.xml]
2012-06-13 04:45:03,411 INFO  [BMW_Accounts] controller.Controller initConfig 
(Controller.java:365) - The controller config has been initialized
2012-06-13 04:45:03,411 INFO  [BMW_Accounts] process.ProcessRunner run 
(ProcessRunner.java:116) - Initializing process engine
2012-06-13 04:45:03,427 INFO  [BMW_Accounts] process.ProcessRunner run 
(ProcessRunner.java:119) - Loading parameters
2012-06-13 04:45:10,431 INFO  [BMW_Accounts] config.LastRun load 
(LastRun.java:96) - Last run info will be saved in file: C:\Program 
Files\salesforce.com\Data 
Loader\cliq_process\BMW_Accounts\log\BMW_Accounts_lastRun.properties
2012-06-13 04:45:10,525 INFO  [BMW_Accounts] process.ProcessRunner run 
(ProcessRunner.java:127) - Logging in to: https://login.salesforce.com
2012-06-13 04:45:10,525 INFO  [BMW_Accounts] client.PartnerClient login 
(PartnerClient.java:478) - Beginning Partner Salesforce login ....
2012-06-13 04:45:10,556 INFO  [BMW_Accounts] client.PartnerClient loginInternal 
(PartnerClient.java:519) - Salesforce login to 
https://login.salesforce.com/services/Soap/u/24.0 as user hrowen@tquila.com
2012-06-13 04:45:15,064 INFO  [BMW_Accounts] dao.DataAccessObjectFactory 
getDaoInstance (DataAccessObjectFactory.java:51) - Instantiating data access 
object: C:\Program Files\salesforce.com\Data 
Loader\cliq_process\BMW_Accounts\read\BMW_Accounts.csv of type: csvRead
2012-06-13 04:45:15,064 INFO  [BMW_Accounts] process.ProcessRunner run 
(ProcessRunner.java:132) - Checking the data access object connection
2012-06-13 04:45:15,080 INFO  [BMW_Accounts] process.ProcessRunner run 
(ProcessRunner.java:137) - Setting field types
2012-06-13 04:45:36,140 ERROR [BMW_Accounts] client.PartnerClient runOperation 
(PartnerClient.java:332) - Error while calling web service operation: 
describeSObject, error was: Failed to send request to 
https://eu1-api.salesforce.com/services/Soap/u/24.0/00D90000000cxCM
com.sforce.ws.ConnectionException: Failed to send request to 
https://eu1-api.salesforce.com/services/Soap/u/24.0/00D90000000cxCM
    at com.sforce.ws.transport.SoapConnection.send(SoapConnection.java:120)
    at com.sforce.soap.partner.PartnerConnection.describeSObject(PartnerConnection.java:1115)
    at com.salesforce.dataloader.client.PartnerClient$10.run(PartnerClient.java:185)
    at com.salesforce.dataloader.client.PartnerClient$10.run(PartnerClient.java:177)
    at com.salesforce.dataloader.client.PartnerClient.runOperation(PartnerClient.java:328)
    at com.salesforce.dataloader.client.PartnerClient.describeSObject(PartnerClient.java:723)
    at com.salesforce.dataloader.client.PartnerClient.setFieldTypes(PartnerClient.java:676)
    at com.salesforce.dataloader.controller.Controller.setFieldTypes(Controller.java:133)
    at com.salesforce.dataloader.process.ProcessRunner.run(ProcessRunner.java:138)
    at com.salesforce.dataloader.process.ProcessRunner.run(ProcessRunner.java:100)
    at com.salesforce.dataloader.process.ProcessRunner.main(ProcessRunner.java:253)
Caused by: java.net.ConnectException: Connection timed out: connect
    at java.net.PlainSocketImpl.socketConnect(Native Method)
    at java.net.PlainSocketImpl.doConnect(Unknown Source)
    at java.net.PlainSocketImpl.connectToAddress(Unknown Source)
    at java.net.PlainSocketImpl.connect(Unknown Source)
    at java.net.SocksSocketImpl.connect(Unknown Source)
    at java.net.Socket.connect(Unknown Source)
    at com.sun.net.ssl.internal.ssl.SSLSocketImpl.connect(Unknown Source)
    at sun.net.NetworkClient.doConnect(Unknown Source)
    at sun.net.www.http.HttpClient.openServer(Unknown Source)
    at sun.net.www.http.HttpClient.openServer(Unknown Source)
    at sun.net.www.protocol.https.HttpsClient.<init>(Unknown Source)
    at sun.net.www.protocol.https.HttpsClient.New(Unknown Source)
    at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(Unknown Source)
    at sun.net.www.protocol.http.HttpURLConnection.plainConnect(Unknown Source)
```

Original comment by `paddybut...@gmail.com` on 13 Jun 2012 at 8:22

**Comment by GoogleCodeExporter** [comment]
```
When it logs in, it will connect to:
https://login.salesforce.com/services/Soap/u/24.0

After logging in, all requests will go to:
https://eu1-api.salesforce.com/services/Soap/u/24.0/00D90000000cxCM

I'm not knowledgeable about Windows 7 to know why this is being blocked, but it 
sounds like it is a UAC related issue since it works when you run it directly.


```

Original comment by `vijay.swamidass@gmail.com` on 13 Jun 2012 at 9:47

**Comment by GoogleCodeExporter** [comment]
```
Since it works when run manually, it is not a CLIq issue.
Perhaps there is a network security restriction on the user when it is 
scheduled.  I wish I could help more, but since it isn't a CLIq error, there 
isn't much I can do.
```

Original comment by `vijay.swamidass@gmail.com` on 18 Nov 2012 at 12:53
- Changed state: **Invalid**
