### ISSUE TITLE
Class definition missing 

### ISSUE THREAD

**Issue by GoogleCodeExporter** [LeoLiXX/dataloadercliq#55]
```
What steps will reproduce the problem?
1. Open cliq.bat
2. Select "Export" at the UI
3. Enter the process Name and click "Next"

What is the expected output? What do you see instead?
I should have seen the next screen at the UI but instead I get this error at 
the cmd screen :

Exception occurred during event dispatching:
java.lang.NoClassDefFoundError: com/sforce/soap/partner/fault/ApiFault
        at com.salesforce.cliq.cliconfig.CliConfigFactory.getCliConfig(Unknown S
ource)
        at com.salesforce.cliq.cliconfig.CliConfigFactory.getCliConfig(Unknown S
ource)
        at com.salesforce.cliq.ui.OperationPanelDescriptor.aboutToHidePanel(Unkn
own Source)
        at com.nexes.wizard.Wizard.setCurrentPanel(Unknown Source)
        at com.nexes.wizard.WizardController.nextButtonPressed(Unknown Source)
        at com.nexes.wizard.WizardController.actionPerformed(Unknown Source)
        at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:18
49)
        at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.jav
a:2169)
        at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel
.java:420)
        at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:258
)
        at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonL
istener.java:234)
        at java.awt.Component.processMouseEvent(Component.java:5488)
        at javax.swing.JComponent.processMouseEvent(JComponent.java:3126)
        at java.awt.Component.processEvent(Component.java:5253)
        at java.awt.Container.processEvent(Container.java:1966)
        at java.awt.Component.dispatchEventImpl(Component.java:3955)
        at java.awt.Container.dispatchEventImpl(Container.java:2024)
        at java.awt.Component.dispatchEvent(Component.java:3803)
        at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4212
)
        at java.awt.LightweightDispatcher.processMouseEvent(Container.java:3892)

        at java.awt.LightweightDispatcher.dispatchEvent(Container.java:3822)
        at java.awt.Container.dispatchEventImpl(Container.java:2010)
        at java.awt.Window.dispatchEventImpl(Window.java:1774)
        at java.awt.Component.dispatchEvent(Component.java:3803)
        at java.awt.EventQueue.dispatchEvent(EventQueue.java:463)
        at java.awt.EventDispatchThread.pumpOneEventForHierarchy(EventDispatchTh
read.java:242)
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThre
ad.java:163)
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThre
ad.java:153)
        at java.awt.Dialog$1.run(Dialog.java:515)
        at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:209)
        at java.awt.EventQueue.dispatchEvent(EventQueue.java:461)
        at java.awt.EventDispatchThread.pumpOneEventForHierarchy(EventDispatchTh
read.java:242)
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThre
ad.java:163)
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:157)

        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:149)

        at java.awt.EventDispatchThread.run(EventDispatchThread.java:110)


What version of the product are you using? On what operating system?
I am using Apex DataLoader 23.0 in Windows 7 and the latest CLIq version 2.2.0

Please provide any additional information below.
I have no idea from where this error popped up. Please help. Thanks.
```

Original issue reported on code.google.com by `mand...@gmail.com` on 19 Jun 2012 at 3:59

**Comment by GoogleCodeExporter** [comment]
```
With dataloader 23.0, use cliq 2.1.1.  The locations of the classes changed 
after 24.0 so there are compatibility problems.
```

Original comment by `vijay.swamidass@gmail.com` on 19 Jun 2012 at 6:19

**Comment by GoogleCodeExporter** [comment]
```
Thanks. CLIq 2.1.1 worked with DL 23.0. Now when I try to export, the directory 
by default is : C:\Program Files (x86)\salesforce.com\Apex Data Loader 
23.0\cliq_process\export_Leads. And when I click "Create Data Loader CLI 
Files", it now says "Access is denied" and if I double click it, it says 
"Directory already exists. Please delete it first". Could you put some light 
here? Thanks.
```

Original comment by `mand...@gmail.com` on 19 Jun 2012 at 9:10

**Comment by GoogleCodeExporter** [comment]
```
This might be due to the User Access Control on windows.  You might try turning 
off the UAC:
http://code.google.com/p/dataloadercliq/wiki/Troubleshooting
```

Original comment by `vijay.swamidass@gmail.com` on 20 Jun 2012 at 7:56

**Comment by GoogleCodeExporter** [comment]
```
But we are using our systems most of the time in an organization where UAC is 
enabled and cannot be disabled except by someone from the Administration 
department. And they wouldn't advise turning it off. Hence, there should be an 
option for us to change the directory path while trying to export itself at 
CLIq UI. 

And I think I read somewhere here that this has been accepted as a future 
enhancement. If you working on it, it would be great to release this sooner. I 
will be looking forward for it. Thanks.
```

Original comment by `mand...@gmail.com` on 21 Jun 2012 at 3:33

**Comment by GoogleCodeExporter** [comment]
Original comment by `vijay.swamidass@gmail.com` on 28 Jun 2012 at 7:07
- Changed state: **Accepted**
- Added labels: **Type-Enhancement**
- Removed labels: **Type-Defect**

**Comment by GoogleCodeExporter** [comment]
```
http://code.google.com/p/dataloadercliq/issues/detail?id=48

I will try to create a way to put the cliq_process files in a different 
directory than the Program Files area.
```

Original comment by `vijay.swamidass@gmail.com` on 18 Nov 2012 at 12:58
- Changed state: **Duplicate**
