### ISSUE TITLE
Loads fail with NullPointerException after switching to DL 25.0.1 (CLIq 2.2.0)(UNIX)

### ISSUE THREAD

**Issue by GoogleCodeExporter** [LeoLiXX/dataloadercliq#59]
```
What steps will reproduce the problem?
1. Replace DataLoader.jar (DL 22) with dataloader-25.0.1-uber.jar
2. Modify <process>.sh for new .jar name
3. Modify process-conf.xml for sfdc.endpoint =
         https://test.salesforce.com/services/Soap/u/25.0
4. Run the process

What is the expected output? What do you see instead?

Expect a successful process generating the standard success and error .csv.   
I’ve attempted both UPSERT and DELETE (soft). What I see is the following 
error:
[AccountDelete] process.ProcessRunner topLevelError (ProcessRunner.java:238) - 
Unable to run process AccountDelete
java.lang.NullPointerException
<<Full output provided at the bottom>>

What version of the product are you using? On what operating system?
DataLoader 25.0.1 
CLIq 2.2.0
Java 1.6.0
OS: AIX aix114 1 6 00F649F14C00  (uname –a)


Please provide any additional information below.

Have many processes running today under DL 22 and am attempting to upgrade to 
DL 25.  After replacing DataLoader.jar with  dataloader-25.0.1-uber.jar on the 
AIX box I modified the <process>.sh with the new .jar name and modified the 
process-conf.xml updating the endpoint for the services/Soap/u/25.0 (this 
change was identified by comparing the original .xml with one generated using 
the newer version of CLIq 2.2.0 (original .xml generated using 1.4.22).  The 
endpoint and the inclusion of empty proxy settings are the only differences I 
noticed.

=== Full Output ======================
2012-08-09 10:45:54,004 INFO  [main] controller.Controller initLog 
(Controller.java:388) - The log has been initialized
2012-08-09 10:45:54,010 INFO  [main] process.ProcessConfig getBeanFactory 
(ProcessConfig.java:103) - Loading process configuration from config file: 
/home/apps/hrc/salesforce/Apex_Data_Loader_22.0/cliq_process/Account/AccountDele
te/config/process-conf.xml 
2012-08-09 10:45:54,138 INFO  [main] xml.XmlBeanDefinitionReader 
loadBeanDefinitions (XmlBeanDefinitionReader.java:315) - Loading XML bean 
definitions from file 
[/home/apps/hrc/salesforce/Apex_Data_Loader_22.0/cliq_process/Account/AccountDel
ete/config/process-conf.xml]
2012-08-09 10:45:54,239 FATAL [AccountDelete] process.ProcessRunner 
topLevelError (ProcessRunner.java:238) - Unable to run process AccountDelete
java.lang.NullPointerException
at com.salesforce.dataloader.controller.Controller.<init>(Controller.java:105)
at 
com.salesforce.dataloader.controller.Controller.getInstance(Controller.java:211)
at com.salesforce.dataloader.process.ProcessRunner.run(ProcessRunner.java:110)
at com.salesforce.dataloader.process.ProcessRunner.run(ProcessRunner.java:100)
at com.salesforce.dataloader.process.ProcessRunner.main(ProcessRunner.java:253)


```

Original issue reported on code.google.com by `ted.hutz...@gmail.com` on 9 Aug 2012 at 3:51

**Comment by GoogleCodeExporter** [comment]
```
[deleted comment]
```

**Comment by GoogleCodeExporter** [comment]
```
I am seeing the exact same problem with dataloader-26.0.0-uber.jar (on SuSE 
FUSE Linux 6.0.0 w/Java 1.6), for what it's worth. I was upgrading from 
DataLoader 21.0.4.
```

Original comment by `d...@mailcan.com` on 12 Oct 2012 at 11:15

**Comment by GoogleCodeExporter** [comment]
Original comment by `vijay.swamidass@gmail.com` on 16 Oct 2012 at 4:37
- Changed state: **Accepted**
- Added labels: **Priority-High**
- Removed labels: **Priority-Medium**

**Comment by GoogleCodeExporter** [comment]
```
Can you post your process-conf.xml?  (without the passwords/usernames)
```

Original comment by `vijay.swamidass@gmail.com` on 16 Oct 2012 at 4:40

**Comment by GoogleCodeExporter** [comment]
```
we are having the same issue on the same platform - AIX
```

Original comment by `Bromle...@gmail.com` on 30 Oct 2012 at 3:46

**Comment by GoogleCodeExporter** [comment]
```
i managed to fix this issue a while after my last comment. 
the fix was to use specific class path jar files rather than using a wildcard

e.g. java -cp pathToUberJar/uberjar.jar <processRunner with main class> 
<parameters>

rather than 

java -cp pathToUberJar/* <processRunner with main class> <parameters>

I hope this helps. I'll update this in the morning when I get in to work with 
specifics.
```

Original comment by `Bromle...@gmail.com` on 30 Oct 2012 at 7:18

**Comment by GoogleCodeExporter** [comment]
```
Ok - if you had both dataloader jar files, it was probably picking up the wrong 
one.
```

Original comment by `vijay.swamidass@gmail.com` on 18 Nov 2012 at 12:51
- Changed state: **Invalid**

**Comment by GoogleCodeExporter** [comment]
```
I am also getting the same error in AIX, but its working in Solaris. I tried 
with giving the jar file path with jar file name, but getting the same error. 
Can anybody help me in resolving the issue. 
```

Original comment by `joice...@gmail.com` on 7 Dec 2012 at 6:34

**Comment by GoogleCodeExporter** [comment]
```
If it is working in Solaris, look at the differences.
- Are the versions of Java different?
- The versions of dataloader.jar?
- Are all the paths correct?
```

Original comment by `vijay.swamidass@gmail.com` on 7 Dec 2012 at 11:02

**Comment by GoogleCodeExporter** [comment]
```
Java version in Solaris:
java version "1.6.0_20"
Java(TM) SE Runtime Environment (build 1.6.0_20-b02)
Java HotSpot(TM) Server VM (build 16.3-b01, mixed mode)

Java Version in AIX:
java version "1.6.0"
Java(TM) SE Runtime Environment (build pap6460sr9fp1-20110208_03(SR9 FP1))
IBM J9 VM (build 2.4, JRE 1.6.0 IBM J9 2.4 AIX ppc64-64 
jvmap6460sr9-20110203_74623 (JIT enabled, AOT enabled)
J9VM - 20110203_074623
JIT  - r9_20101028_17488ifx3
GC   - 20101027_AA)
JCL  - 20110203_01

Both are 1.6 but solaris it is 1.6.0_20 .Will it make any difference? 

Dataloader.jar is dataloader-25.0.2-uber.jar in both Solaris and AIX

Can u specify detail about the path, which all path i should look ? 
$Java_home is set but i can see differences in $PATH 
Also there was 1.5 version eralier and they upgraded to 1.6 and only $JAVA_HOME 
is set i think all the other path are pointing to 1.5 version.but i didnt get 
any version error so i didnt give much attention. 

Please find more detail on : 
http://code.google.com/p/dataloadercliq/issues/detail?id=67

Please reply
```

Original comment by `joice...@gmail.com` on 10 Dec 2012 at 6:42

**Comment by GoogleCodeExporter** [comment]
```
After a major battle with this, I realised we could install 
apexdataloader-17.zip and run with 
com.salesforce.lexiloader.process.ProcessRunner not 
com.salesforce.dataloader.process.ProcessRunner. Also change your 
process-conf.xml  <entry key="sfdc.endpoint" 
value="https://test.salesforce.com/services/Soap/u/16.0"/>
<bean id="whatever" class="com.salesforce.lexiloader.process.ProcessRunner" 
singleton="false">
java -cp 
dataloader/lexiloader/LexiLoader_v16.app/Contents/Resources/Java/DataLoader.jar 
com.salesforce.lexiloader.process.ProcessRunner process.name=whatever
```

Original comment by `MBattal...@gmail.com` on 14 Feb 2013 at 3:08

Attachments:
- [apexdataloader-17.zip](https://storage.googleapis.com/google-code-attachments/dataloadercliq/issue-59/comment-11/apexdataloader-17.zip)

**Comment by GoogleCodeExporter** [comment]
```
Working Solution: 

1) cut your dataloader folder from salesformce.com foler . 
2) past it in C drive (out of progaram(86)) folder. 


Now you run from here . it will work !!!! :)
```

Original comment by `spra...@ciphercloud.com` on 26 Dec 2014 at 7:09
